apiVersion: apps/v1
kind: Deployment
metadata:
  name: hafizjh-deployment
  labels:
    app: hafizjh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hafizjh
  template:
    metadata:
      labels:
        app: hafizjh
    spec:
      containers:
      - name: web
        image: hafizjh/project01
        ports:
        - containerPort: 80
