apiVersion: v1
kind: Service
metadata:
  name: hafizjh-service
spec:
  type: NodePort
  selector:
    myapp: hafizjh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hafizjh
  labels:
    myapp: hafizjh
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: hafizjh
  template:
    metadata:
      labels:
        myapp: hafizjh
    spec:
      containers:
      - name: web
        image: jaibw/frozenyogurtshop
        ports:
        - containerPort: 80
