name: website project
on: push
jobs:
  building-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Clean
        continue-on-error: true
        run: docker stop project01 && docker rm project01 && docker rmi hafizjh/project01
      - name: Build Image 
        run: docker build -t hafizjh/project01 .
      - name: kube-deploy
        run: kubectl apply -f deployment.yaml
      - name: list deployments
        run: kubectl get deployments
